### ISSUE TITLE
Could not open file /opt/dvtb/models/caffenet-yos/caffenet-yos-weights

### ISSUE THREAD

**Issue by hlalibe** [fishcorn/dvtb-container#3]
Hi,

I installed with Docker

When I launch the container i get this prompt: developer@d6c8b1d52a74:/opt/dvtb$

So then I supposed I had to run to start the visualisation tool: ./run_toolbox.py

But that gives me this error: 
Could not open file /opt/dvtb/models/caffenet-yos/caffenet-yos-weights

Then I saw from this post:
https://github.com/yosinski/deep-visualization-toolbox/issues/145
that i have to run these commands to download these files that are missing from the container:
```
cd models/caffenet-yos/
./fetch.sh all
```

Did you have to do this as well ?

But then, when i re-start the container after shutting down the computer, do I need to download these files all again ? They are pretty big and takes time.

**Comment by hlalibe** [comment]
I've managed to dowload the .gz file and extract them, so i could go a bit further, the tool runs for a while then ends up with:
```
CaffeVisApp mode (in CaffeProcThread): GPU
JPGVisLoadingThread.run called
F0818 09:45:28.533731    28 pooling_layer.cu:212] Check failed: error == cudaSuccess (8 vs. 0)  invalid device function
*** Check failure stack trace: ***
```
did you ever encounter this message ?

**Comment by fishcorn** [comment]
Hi, I am not actively developing this project anymore but if you find a solution I'm happy to look at a merge request.

**Comment by hlalibe** [comment]
I managed to bypass the message above by setting this line to False in opt/dvtb/settings.py
caffevis_mode_gpu = locals().get('caffevis_mode_gpu', False)

now i get to the user interface and it seems to work fine, although i don't know at this stage if performance is still ok.
